# Generated by Django 6.0.5 on 2026-05-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='replied',
            field=models.BooleanField(default=False),
        ),
    ]
